import { usePage } from "@inertiajs/react";

export const sunEditorLangEs = {
    code: "es",
    toolbar: {
        default: "Por defecto",
        save: "Guardar",
        font: "Fuente",
        formats: "Formatos",
        fontSize: "Tamaño",
        bold: "Negrita",
        underline: "Subrayado",
        italic: "Cursiva",
        strike: "Tachado",
        subscript: "Subíndice",
        superscript: "Superíndice",
        removeFormat: "Quitar formato",
        fontColor: "Color de fuente",
        hiliteColor: "Color de fondo",
        indent: "Aumentar sangría",
        outdent: "Disminuir sangría",
        align: "Alinear",
        alignLeft: "Alinear a la izquierda",
        alignRight: "Alinear a la derecha",
        alignCenter: "Alinear al centro",
        alignJustify: "Justificar ",
        list: "Lista",
        orderList: "Lista numerada",
        unorderList: "Lista con viñetas",
        horizontalRule: "Línea horizontal",
        hr_solid: "",
        hr_dotted: "",
        hr_dashed: "",
        table: "Tabla",
        link: "Enlace",
        math: "Fórmula",
        image: "Imagen",
        video: "Video",
        audio: "audio",
        fullScreen: "Pantalla completa",
        showBlocks: "Mostrar bloques",
        codeView: "Ver código",
        undo: "Deshacer",
        redo: "Rehacer",
        preview: "Vista previa",
        print: "Imprimir",
        tag_p: "Párrafo",
        tag_div: "Normal (DIV)",
        tag_h: "",
        tag_blockquote: "Cita",
        tag_pre: "Código",
        template: "",
        lineHeight: "Altura de línea",
        paragraphStyle: "Estilo de párrafo",
        textStyle: "Estilo de texto",
        imageGallery: "Galería de imágenes",
        dir_ltr: "Izquierda a derecha",
        dir_rtl: "Derecha a izquierda",
        mention: "Mención",
    },

    dialogBox: {
        linkBox: {
            title: "ítulo",
            url: "URL",
            text: "Texto",
            newWindowCheck: "Abrir en una nueva ventana",
            downloadLinkCheck: "Descargar enlace",
            bookmark: "Marcador",
        },
        mathBox: {
            title: "Titulo",
            inputLabel: "",
            fontSizeLabel: "",
            previewLabel: "",
        },
        imageBox: {
            title: "",
            file: "",
            url: "",
            altText: "",
        },
        videoBox: {
            title: "",
            file: "",
            url: "",
        },
        audioBox: {
            title: "",
            file: "",
            url: "",
        },
        browser: {
            tags: "",
            search: "",
        },
        caption: "",
        close: "",
        submitButton: "",
        revertButton: "",
        proportion: "",
        basic: "",
        left: "",
        right: "",
        center: "",
        width: "",
        height: "",
        size: "",
        ratio: "",
    },
    controller: {
        edit: "Editar",
        unlink: "Desvincular",
        remove: "Eliminar",
        insertRowAbove: "Insertar fila arriba",
        insertRowBelow: "Insertar fila abajo",
        deleteRow: "Eliminar fila",
        insertColumnBefore: "Insertar columna antes",
        insertColumnAfter: "Insertar columna después",
        deleteColumn: "Eliminar columna",
        fixedColumnWidth: "Ancho de columna fijo",
        resize100: "100%",
        resize75: "75%",
        resize50: "50%",
        resize25: "25%",
        autoSize: "Ajuste automático",
        mirrorHorizontal: "Espejo horizontal",
        mirrorVertical: "Espejo vertical",
        rotateLeft: "Rotar a la izquierda",
        rotateRight: "Rotar a la derecha",
        maxSize: "Tamaño máximo",
        minSize: "Tamaño mínimo",
        tableHeader: "Encabezado de tabla",
        mergeCells: "Combinar celdas",
        splitCells: "Dividir celdas",
        HorizontalSplit: "Dividir horizontalmente",
        VerticalSplit: "Dividir verticalmente",
    },

    menu: {
        spaced: "Espaciado",
        bordered: "Con borde",
        neon: "Neón",
        translucent: "Translúcido",
        shadow: "Sombra",
        code: "Código",
    },
};

export const appUrl = "http://procesosacademicos.buap.mx/vd/public";
export const getFullUrl = (path: string): string => {
    if (path.startsWith("http")) {
        return path; // Ya es una URL completa
    }

    // Asegurar que el path comience con /
    const normalizedPath = path.startsWith("/") ? path : `/${path}`;

    // Si appUrl ya termina con /public, usar directamente
    return `${appUrl}${normalizedPath}`;
};
