import { usePage } from "@inertiajs/react";

export const sunEditorLangEs = {
    code: "es",
    toolbar: {
        default: "Por defecto",
        save: "Guardar",
        font: "Fuente",
        formats: "Formatos",
        fontSize: "Tamaño",
        bold: "Negrita",
        underline: "Subrayado",
        italic: "Cursiva",
        strike: "Tachado",
        subscript: "Subíndice",
        superscript: "Superíndice",
        removeFormat: "Quitar formato",
        fontColor: "Color de fuente",
        hiliteColor: "Color de fondo",
        indent: "Aumentar sangría",
        outdent: "Disminuir sangría",
        align: "Alinear",
        alignLeft: "Alinear a la izquierda",
        alignRight: "Alinear a la derecha",
        alignCenter: "Alinear al centro",
        alignJustify: "Justificar ",
        list: "Lista",
        orderList: "Lista numerada",
        unorderList: "Lista con viñetas",
        horizontalRule: "Línea horizontal",
        hr_solid: "",
        hr_dotted: "",
        hr_dashed: "",
        table: "Tabla",
        link: "Enlace",
        math: "Fórmula",
        image: "Imagen",
        video: "Video",
        audio: "audio",
        fullScreen: "Pantalla completa",
        showBlocks: "Mostrar bloques",
        codeView: "Ver código",
        undo: "Deshacer",
        redo: "Rehacer",
        preview: "Vista previa",
        print: "Imprimir",
        tag_p: "Párrafo",
        tag_div: "Normal (DIV)",
        tag_h: "",
        tag_blockquote: "Cita",
        tag_pre: "Código",
        template: "",
        lineHeight: "Altura de línea",
        paragraphStyle: "",
        textStyle: "",
        imageGallery: "",
        dir_ltr: "",
        dir_rtl: "",
        mention: "",
    },

    dialogBox: {
        linkBox: {
            title: "",
            url: "",
            text: "",
            newWindowCheck: "",
            downloadLinkCheck: "",
            bookmark: "",
        },
        mathBox: {
            title: "",
            inputLabel: "",
            fontSizeLabel: "",
            previewLabel: "",
        },
        imageBox: {
            title: "",
            file: "",
            url: "",
            altText: "",
        },
        videoBox: {
            title: "",
            file: "",
            url: "",
        },
        audioBox: {
            title: "",
            file: "",
            url: "",
        },
        browser: {
            tags: "",
            search: "",
        },
        caption: "",
        close: "",
        submitButton: "",
        revertButton: "",
        proportion: "",
        basic: "",
        left: "",
        right: "",
        center: "",
        width: "",
        height: "",
        size: "",
        ratio: "",
    },
    controller: {
        edit: "",
        unlink: "",
        remove: "",
        insertRowAbove: "",
        insertRowBelow: "",
        deleteRow: "",
        insertColumnBefore: "",
        insertColumnAfter: "",
        deleteColumn: "",
        fixedColumnWidth: "",
        resize100: "",
        resize75: "",
        resize50: "",
        resize25: "",
        autoSize: "",
        mirrorHorizontal: "",
        mirrorVertical: "",
        rotateLeft: "",
        rotateRight: "",
        maxSize: "",
        minSize: "",
        tableHeader: "",
        mergeCells: "",
        splitCells: "",
        HorizontalSplit: "",
        VerticalSplit: "",
    },

    menu: {
        spaced: "Espaciado",
        bordered: "Con borde",
        neon: "Neón",
        translucent: "Translúcido",
        shadow: "Sombra",
        code: "Código",
    },
};

export const appUrl = "http://localhost/vd/public";
export const getFullUrl = (path: string): string => {
    if (path.startsWith("http")) {
        return path; // Ya es una URL completa
    }

    // Asegurar que el path comience con /
    const normalizedPath = path.startsWith("/") ? path : `/${path}`;

    // Si appUrl ya termina con /public, usar directamente
    return `${appUrl}${normalizedPath}`;
};
