import { usePage } from "@inertiajs/react";

export const sunEditorLangEs = {
    code: "es",
    toolbar: {
        default: "Por defecto",
        save: "Guardar",
        font: "Fuente",
        formats: "Formatos",
        fontSize: "Tamaño",
        bold: "Negrita",
        underline: "Subrayado",
        italic: "Cursiva",
        strike: "Tachado",
        subscript: "Subíndice",
        superscript: "Superíndice",
        removeFormat: "Quitar formato",
        fontColor: "Color de fuente",
        hiliteColor: "Color de fondo",
        indent: "Aumentar sangría",
        outdent: "Disminuir sangría",
        align: "Alinear",
        alignLeft: "Alinear a la izquierda",
        alignRight: "Alinear a la derecha",
        alignCenter: "Alinear al centro",
        alignJustify: "Justificar ",
        list: "Lista",
        orderList: "Lista numerada",
        unorderList: "Lista con viñetas",
        horizontalRule: "Línea horizontal",
        hr_solid: "",
        hr_dotted: "",
        hr_dashed: "",
        table: "Tabla",
        link: "Enlace",
        math: "Fórmula",
        image: "Imagen",
        video: "Video",
        audio: "audio",
        fullScreen: "Pantalla completa",
        showBlocks: "Mostrar bloques",
        codeView: "Ver código",
        undo: "Deshacer",
        redo: "Rehacer",
        preview: "Vista previa",
        print: "Imprimir",
        tag_p: "Párrafo",
        tag_div: "Normal (DIV)",
        tag_h: "",
        tag_blockquote: "Cita",
        tag_pre: "Código",
        template: "",
        lineHeight: "Altura de línea",
        paragraphStyle: "Estilo de párrafo",
        textStyle: "Estilo de texto",
        imageGallery: "Galería de imágenes",
        dir_ltr: "Izquierda a derecha",
        dir_rtl: "Derecha a izquierda",
        mention: "Mención",
    },
    dialogBox: {
        linkBox: {
            title: "Título",
            url: "URL",
            text: "Texto",
            newWindowCheck: "Abrir en una nueva ventana",
            downloadLinkCheck: "Descargar enlace",
            bookmark: "Marcador",
        },
        mathBox: {
            title: "Título",
            inputLabel: "",
            fontSizeLabel: "",
            previewLabel: "",
        },
        imageBox: {
            title: "Imagen",
            file: "Archivo",
            url: "URL",
            altText: "Texto alternativo",
        },
        videoBox: {
            title: "Video",
            file: "Archivo",
            url: "URL",
        },
        audioBox: {
            title: "Audio",
            file: "Archivo",
            url: "URL",
        },
        browser: {
            tags: "Etiquetas",
            search: "Buscar",
        },
        caption: "Leyenda",
        close: "Cerrar",
        submitButton: "Aceptar",
        revertButton: "Revertir",
        proportion: "Proporción",
        basic: "Básico",
        left: "Izquierda",
        right: "Derecha",
        center: "Centro",
        width: "Ancho",
        height: "Alto",
        size: "Tamaño",
        ratio: "Relación",
    },
    controller: {
        edit: "Editar",
        unlink: "Desvincular",
        remove: "Eliminar",
        insertRowAbove: "Insertar fila arriba",
        insertRowBelow: "Insertar fila abajo",
        deleteRow: "Eliminar fila",
        insertColumnBefore: "Insertar columna antes",
        insertColumnAfter: "Insertar columna después",
        deleteColumn: "Eliminar columna",
        fixedColumnWidth: "Ancho de columna fijo",
        resize100: "100%",
        resize75: "75%",
        resize50: "50%",
        resize25: "25%",
        autoSize: "Ajuste automático",
        mirrorHorizontal: "Espejo horizontal",
        mirrorVertical: "Espejo vertical",
        rotateLeft: "Rotar a la izquierda",
        rotateRight: "Rotar a la derecha",
        maxSize: "Tamaño máximo",
        minSize: "Tamaño mínimo",
        tableHeader: "Encabezado de tabla",
        mergeCells: "Combinar celdas",
        splitCells: "Dividir celdas",
        HorizontalSplit: "Dividir horizontalmente",
        VerticalSplit: "Dividir verticalmente",
    },
    menu: {
        spaced: "Espaciado",
        bordered: "Con borde",
        neon: "Neón",
        translucent: "Translúcido",
        shadow: "Sombra",
        code: "Código",
    },
};

// Detecta el protocolo (http o https) y el host dinámicamente
export const appUrl = `${window.location.protocol}//${window.location.host}/vd/public`;

// Normaliza la URL de un recurso
export const getFullUrl = (path: string): string => {
    if (!path) return appUrl;
    if (path.startsWith("http")) {
        return path; // Ya es URL completa
    }
    const normalizedPath = path.startsWith("/") ? path : `/${path}`;
    return `${appUrl}${normalizedPath}`;
};
